- name: Déployer l'API sur GCP
  hosts: api
  become: yes

  vars:
    github_token: "{{ lookup('env', 'GH_PAT') }}"
    repo_url: "https://{{ github_token }}@github.com/temp-account-vm/gcp-ci-cd-api.git"
    app_path: "/home/debian/api"

  tasks:
    - name: Installer Node.js, npm, Git, PM2
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - curl
        - git
        - nodejs
        - npm

    - name: Installer PM2 globalement
      npm:
        name: pm2
        global: yes

    - name: Cloner ou mettre à jour le repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_path }}"
        version: main
        force: yes

    - name: Installer les dépendances
      npm:
        path: "{{ app_path }}"
        state: present

    - name: Démarrer l'API avec PM2
      command: pm2 start {{ app_path }}/app.js --name api --update-env

    - name: Sauvegarder la config PM2
      command: pm2 save
