- name: Déployer l'API sur GCP
  hosts: api
  become: yes

  vars:
    gh_pat: "{{ gh_pat | default(lookup('env', 'GH_PAT')) }}"
    repo_url: "https://{{ gh_pat }}@github.com/temp-account-vm/gcp-ci-cd-api.git"
    app_root: "/home/debian/api"

  tasks:
    - name: Install dependencies
      apt:
        name:
          - curl
          - nodejs
          - npm
          - git
        state: present
        update_cache: yes

    - name: Ensure app directory exists
      file:
        path: "{{ app_root }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Cloner ou mettre à jour le repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_root }}"
        version: main
        force: yes
      no_log: true

    - name: Installer les dépendances
      npm:
        path: "{{ app_root }}/api"
        production: yes

    - name: Start app with PM2
      shell: |
        npm install -g pm2
        cd {{ app_root }}/api
        pm2 start index.js --name my-api || pm2 restart my-api
        pm2 save
      args:
        executable: /bin/bash
