- name: Déployer l'API sur GCP
  hosts: api
  become: yes

  vars:
    gh_pat: "{{ gh_pat | default(lookup('env', 'GH_PAT')) }}"
    repo_url: "https://{{ gh_pat }}@github.com/temp-account-vm/gcp-ci-cd-api.git"
    app_root: "/home/debian/api"

  tasks:
    - name: Install dependencies
      apt:
        name:
          - curl
          - git
        state: present
        update_cache: yes

    - name: Install the gpg key for nodejs
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
    
    - name: Install the nodejs 22 repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_22.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present

    - name: Check npm version
      command: npm -v
      register: npm_version
    - debug:
        var: npm_version.stdout

    - name: Ensure app directory exists
      file:
        path: "{{ app_root }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_root }}"
        version: main
        force: yes
      no_log: true

    - name: Install npm dependencies
      npm:
        path: "{{ app_root }}/api"
        production: yes

    - name: Start app with PM2
      shell: |
        npm install -g pm2
        cd {{ app_root }}/api
        pm2 start index.js --name my-api || pm2 restart my-api
        pm2 save
      args:
        executable: /bin/bash
